version = "0.0.1"
enabled = true

[[site]]
domain = "site.local.test"
r3ply = "cli.r3ply.test"
signet = "45HH6mQ8aRRy8CsvRmtQ2w"
issued = "2025-11-15"
label = "CLI"

[[site]]
domain = "b00k.club"
r3ply = "r3ply.com"
signet = "gchTwqHz8qmbMt1_SdDi3w"
issued = 2025-11-19
label = "production"

[comments]
"paths*" = ["!/", "!{,/}comments{,/}", "/works/**"]

[comments.email]
enabled = true
"&comment_{}" = "comment.template.md"

[moderation]
enabled = true
github = [ ]
webhook = [ ]

  [[moderation.local]]
  "file_path_{}" = "content/comments/{{ comment.ts_rcvd }}_{{ comment.id[:8] }}-{{ author.pseudonym[:7] }}.md"
  enabled = true